name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          
          yarn install
          yarn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REACT_APP_CTF_SPACE_ID: ${{ secrets.REACT_APP_CTF_SPACE_ID }}
          REACT_APP_CTF_CDN_TOKEN: ${{ secrets.REACT_APP_CTF_CDN_TOKEN }}
          REACT_APP_CTF_PREVIEW_TOKEN: ${{ secrets.REACT_APP_CTF_PREVIEW_TOKEN }}
